name: Windows Build (Subspace)

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (Debug/Release)'
        required: false
        type: string
        default: 'Release'

jobs:
  build_windows:
    runs-on: windows-2025
    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v5

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        cache: true
        install: >-
          git base-devel make unzip
        pacboy: >-
          toolchain:p
          fc:p
          cmake:p
          ninja:p
          libusb:p
          boost:p
          fftw:p

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        target: 'desktop'
        arch: 'win64_mingw'
        modules: 'qtmultimedia qtserialport'
        cache: true

    - name: Download Hamlib
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'hamlib/hamlib'
        fileName: 'hamlib-w64-4.6.5.zip'
        tag: '4.6.5'
        extract: true
        out-file-path: 'local/hamlib-tmp'

    - name: Setup Hamlib
      shell: msys2 {0}
      run: |
        mv local/hamlib-tmp/hamlib-w64-4.6.5 local/hamlib
        mv local/hamlib/lib/gcc/libhamlib.dll.a local/hamlib/lib/libhamlib.dll.a

    - name: Configure
      shell: msys2 {0}
      run: |
        cmake -B build \
          -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/local/hamlib;${QT_ROOT_DIR}" \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type || 'Release' }} \
          -DCMAKE_Fortran_FLAGS="-static-libgfortran -static-libquadmath" \
          -DFFTW3F_LIBRARY=/mingw64/lib/libfftw3f.a

    - name: Build
      shell: msys2 {0}
      run: cmake --build build -j$(nproc)

    - name: Package
      shell: msys2 {0}
      run: |
        cp build/JS8Call.exe build/JS8Call/
        cp build/JS8Call/LICENSE build/JS8Call/ 2>/dev/null || true
        cp local/hamlib/bin/libhamlib-4.dll build/JS8Call/
        cp local/hamlib/bin/libusb-1.0.dll build/JS8Call/
        cp local/hamlib/bin/libwinpthread-1.dll build/JS8Call/

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: "JS8Call-Subspace_${{ github.sha }}_win64"
        path: ./build/JS8Call/
